// frontend/src/components/Card.vue
<template>
    <div class="col-span-1 bg-white rounded-lg shadow divide-y divide-gray-200">
      <div class="w-full flex items-center justify-between p-6 space-x-6">
        <div class="flex-1 truncate">
          <p class="mt-1 text-gray-500 text-sm truncate">{{ 'premiere blague' }}</p>
        </div>
        <a href="#">
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg>
        </a>
      </div>
    </div>
</template>

<script>
import { MailIcon, PhoneIcon } from '@heroicons/vue/solid'

const person = [
  {
    name: 'Jane Cooper',
    title: 'Regional Paradigm Technician',
    role: 'Admin',
    email: 'janecooper@example.com',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60',
  },
  // More people...
]

export default {
  name: 'Card',
  components: {
    MailIcon,
    PhoneIcon,
  },
  setup() {
    return {
      person,
    }
  },
}
</script>

// frontend/src/components/Card.jsx
import { MailIcon, PhoneIcon } from '@heroicons/react/solid'
import { useState } from 'react'

const people = [
  {
    name: 'Jane Cooper',
    title: 'Regional Paradigm Technician',
    role: 'Admin',
    email: 'janecooper@example.com',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60',
  },
]

export default function Card() {
  return (
    <>
      {people.map((person) => (
        <li key={person.email} className="col-span-1 bg-white rounded-lg shadow divide-y divide-gray-200">
          <div className="w-full flex items-center justify-between p-6 space-x-6">
            <div className="flex-1 truncate">
              <p className="mt-1 text-gray-500 text-sm truncate">{person.title}</p>
            </div>
          </div>
        </li>
      ))}
    </>
  )
}
