// vue-client/src/components/Card.vue
<template>
      <div
      class="flex justify-center py-4 px-8 mb-2 rounded-md cursor-pointer"
      :class="[selected ? `${bgColor} bg-opacity-50 shadow-md` : bgColor]"
        >
          <p class="text-xl"
          :class="[ selected ? 'text-white font-semibold underline' : 'text-gray-700 font-medium']"
          >
          {{ title }}
          </p>
        </div>
</template>

<script lang="ts">
import { mapState, mapGetters} from 'vuex'

export default{
  name: 'Card',
  data() {
    return {}
  },
  props: {
    title: {
      type: String
    },
    selected: {
      type: Boolean
    },
    bgColor: {
      type: String
    }
  },
  methods: {}
}
</script>

// react-client/src/components/Card.tsx
import React, { useState } from 'react'

export default function Card({ card, bgColor, selected }) {
  const [active, setActive] = useState(false)
  function toggleClick() {
    setActive(!active)
  }
  return (
    <>
      <div
        onClick={toggleClick}
        className={`flex justify-center py-4 px-8 mb-2 rounded-md cursor-pointer ${
          // :class="[selected ? `${bgColor} bg-opacity-50 shadow-md` : bgColor]"
          selected
            ? bgColor +
              ' bg-opacity-60 shadow-lg underline font-semibold text-white'
            : bgColor
        }`}
      >
        <p className="text-xl"> {card.title} </p>
      </div>
    </>
  )
}
